//
//  DetailsMainRouter.swift
//  VIPERTestProgect
//
//  Created by Раис Аглиуллов on 15.08.2020.
//  Copyright (c) 2020 Ильдар Аглиуллов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

@objc protocol DetailsMainRoutingLogic {

}

protocol DetailsMainDataPassing {
    var dataStore: DetailsMainDataStore? { get }
}

class DetailsMainRouter: NSObject, DetailsMainRoutingLogic, DetailsMainDataPassing {
    
    weak var viewController: DetailsMainViewController?
    var dataStore: DetailsMainDataStore?
    
}
