//
//  MainModels.swift
//  VIPERTestProgect
//
//  Created by Раис Аглиуллов on 15.08.2020.
//  Copyright (c) 2020 Ильдар Аглиуллов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum Main {
    
    struct DisplayedSection: Equatable {
        
        enum SectionType: Equatable {
            case main
            case details
        }
        
        let type: SectionType
        
        struct DisplayedCell: Equatable {
            enum CellType: Equatable {
                case info(title: String)
                case description(title: String, imageName: String)
            }
            
            let type: CellType
        }
        
        let cells: [DisplayedCell]
        let header: String?
        let footer: String?
    }
    
    enum FetchTitle {
        struct Request {
            
        }
        
        struct Response {
            let titleOption: [TitleOptions]
        }
        
        struct ViewModel {
            let titleOption: [TitleOptions]
        }
    }
    
    enum FetchOptions {
        struct Request {
            
        }
        
        struct Response {
            let mainOption: [Options]
        }
        
        struct ViewModel {
            let displayedSection: [DisplayedSection]
        }
    }
    
    enum ChangeControllerMode {
        struct Request {
            
        }
        
        struct Response {
            let mode: ControllerMode
        }
        
        struct ViewModel {
            let mode: ControllerMode
        }
    }
    
    enum OpenDetails {
        struct Request {
            let index: Int
        }
        
        struct Response {
            let option: Options
        }
        
        struct ViewModel {
            let option: Options
        }
    }
    
}
