//
//  MainRouter.swift
//  VIPERTestProgect
//
//  Created by Раис Аглиуллов on 15.08.2020.
//  Copyright (c) 2020 Ильдар Аглиуллов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

@objc protocol MainRoutingLogic {
    func routeToDetails()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainDataPassing {
    
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    // MARK: Passing data
    private func passDataToDetails(source: MainDataStore, destination: inout DetailsMainDataStore) {
        destination.option = source.option
    }
    
    // MARK: Navigation
    func navigateToDetails(source: MainViewController, destination: DetailsMainViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
}

extension MainRouter: MainRoutingLogic {
    
    func routeToDetails() {
        guard let viewController = self.viewController else { return }
        
        let detailsVC = DetailsMainViewController()
        guard let sourceDataStore = self.dataStore, var destinationDataStore = detailsVC.router?.dataStore else { return }
        
        self.passDataToDetails(source: sourceDataStore, destination: &destinationDataStore)
        self.navigateToDetails(source: viewController, destination: detailsVC)
    }
    
}
