//
//  MainWorker.swift
//  VIPERTestProgect
//
//  Created by Раис Аглиуллов on 15.08.2020.
//  Copyright (c) 2020 Ильдар Аглиуллов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class MainWorker {
    
    private let networkData: NetworkService = NetworkService()
    
    func getMainOptions(completion: @escaping ([Options]?) -> Void) {
        let fileName = "mainOptions"
        networkData.getDataFromJSON(fileName: fileName, response: completion)
    }
    
    func getTitleOptions(completion: @escaping ([TitleOptions]?) -> Void) {
        let fileName = "titleOptions"
        networkData.getDataFromJSON(fileName: fileName, response: completion)
    }
    
}
